from irv import IRV
from plurality_at_large import PluralityAtLarge
from plurality import Plurality
from ranked_pairs import RankedPairs
from schulze_by_graph import SchulzeMethodByGraph
from schulze_by_graph import SchulzeNPRByGraph
from schulze_method import SchulzeMethod
from schulze_npr import SchulzeNPR
from schulze_pr import SchulzePR
from schulze_stv import SchulzeSTV
from stv import STV
from tie_breaker import TieBreaker
